export const SAMPLE_JOBS = [
  {
    _id: "sample-1",
    title: "Frontend Developer Intern",
    description: "Build polished React interfaces and collaborate with product and design teams.",
    location: "Bangalore",
    experienceLevel: 0,
    salary: "4.5",
    jobType: "Internship",
    position: 2,
    requirements: ["React", "JavaScript", "Tailwind CSS"],
    createdAt: new Date().toISOString(),
    company: {
      name: "PixelForge Labs",
      logo: "",
    },
  },
  {
    _id: "sample-2",
    title: "Backend Node.js Engineer",
    description: "Design robust APIs, optimize DB queries, and improve platform reliability.",
    location: "Remote",
    experienceLevel: 2,
    salary: "10",
    jobType: "Full-time",
    position: 3,
    requirements: ["Node.js", "MongoDB", "REST APIs"],
    createdAt: new Date().toISOString(),
    company: {
      name: "CloudSpring",
      logo: "",
    },
  },
  {
    _id: "sample-3",
    title: "Data Analyst - Entry Level",
    description: "Analyze business data, create dashboards, and generate product insights.",
    location: "Pune",
    experienceLevel: 1,
    salary: "6",
    jobType: "Full-time",
    position: 1,
    requirements: ["SQL", "Power BI", "Excel"],
    createdAt: new Date().toISOString(),
    company: {
      name: "InsightFlow",
      logo: "",
    },
  },
];
