// Fallback/demo data shown only if the live API call in useGetAllJobs fails.
// This is NOT the primary demo dataset — see Backend/seed/seedDemoData.js for
// the real MongoDB-backed demo jobs/companies used in normal operation.
export const SAMPLE_JOBS = [
  {
    _id: "sample-1",
    title: "Frontend Developer Intern",
    description: "Build polished React interfaces and collaborate with product and design teams.",
    location: "Bengaluru",
    experienceLevel: 0,
    salary: "4.5",
    jobType: "Internship",
    position: 2,
    requirements: ["React", "JavaScript", "Tailwind CSS"],
    createdAt: new Date().toISOString(),
    company: { name: "PixelForge Labs", logo: "" },
  },
  {
    _id: "sample-2",
    title: "Backend Node.js Engineer",
    description: "Design robust APIs, optimize DB queries, and improve platform reliability.",
    location: "Remote",
    experienceLevel: 2,
    salary: "10",
    jobType: "Full-time",
    position: 3,
    requirements: ["Node.js", "MongoDB", "REST APIs"],
    createdAt: new Date().toISOString(),
    company: { name: "CloudSpring", logo: "" },
  },
  {
    _id: "sample-3",
    title: "Data Analyst - Entry Level",
    description: "Analyze business data, create dashboards, and generate product insights.",
    location: "Pune",
    experienceLevel: 1,
    salary: "6",
    jobType: "Full-time",
    position: 1,
    requirements: ["SQL", "Power BI", "Excel"],
    createdAt: new Date().toISOString(),
    company: { name: "InsightFlow", logo: "" },
  },
  {
    _id: "sample-4",
    title: "Full Stack Developer (MERN)",
    description: "Own features end-to-end across a React frontend and Node/Express backend.",
    location: "Hyderabad",
    experienceLevel: 3,
    salary: "14",
    jobType: "Full-time",
    position: 2,
    requirements: ["MongoDB", "Express", "React", "Node.js"],
    createdAt: new Date().toISOString(),
    company: { name: "Nimbus Systems", logo: "" },
  },
  {
    _id: "sample-5",
    title: "Machine Learning Engineer",
    description: "Build and deploy ML models for recommendation and ranking systems.",
    location: "Gurugram",
    experienceLevel: 4,
    salary: "22",
    jobType: "Full-time",
    position: 1,
    requirements: ["Python", "TensorFlow", "Scikit-learn"],
    createdAt: new Date().toISOString(),
    company: { name: "NeuralArc AI", logo: "" },
  },
  {
    _id: "sample-6",
    title: "DevOps Engineer",
    description: "Manage CI/CD pipelines and cloud infrastructure across staging and production.",
    location: "Remote",
    experienceLevel: 3,
    salary: "16",
    jobType: "Full-time",
    position: 2,
    requirements: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    createdAt: new Date().toISOString(),
    company: { name: "StratoOps", logo: "" },
  },
  {
    _id: "sample-7",
    title: "UI/UX Designer",
    description: "Design user flows, wireframes and high-fidelity prototypes for web and mobile.",
    location: "Mumbai",
    experienceLevel: 2,
    salary: "9",
    jobType: "Full-time",
    position: 1,
    requirements: ["Figma", "User Research", "Prototyping"],
    createdAt: new Date().toISOString(),
    company: { name: "Studio Loom", logo: "" },
  },
  {
    _id: "sample-8",
    title: "QA Automation Engineer",
    description: "Write automated test suites and improve release quality across the platform.",
    location: "Chennai",
    experienceLevel: 2,
    salary: "8",
    jobType: "Full-time",
    position: 2,
    requirements: ["Selenium", "Cypress", "Test Planning"],
    createdAt: new Date().toISOString(),
    company: { name: "QualitEdge", logo: "" },
  },
  {
    _id: "sample-9",
    title: "Java Backend Developer",
    description: "Build scalable microservices using Spring Boot for a fintech platform.",
    location: "Noida",
    experienceLevel: 3,
    salary: "15",
    jobType: "Full-time",
    position: 2,
    requirements: ["Java", "Spring Boot", "Microservices"],
    createdAt: new Date().toISOString(),
    company: { name: "LedgerWorks", logo: "" },
  },
  {
    _id: "sample-10",
    title: "Cybersecurity Analyst",
    description: "Monitor threats, run vulnerability assessments and strengthen security posture.",
    location: "Delhi NCR",
    experienceLevel: 3,
    salary: "13",
    jobType: "Full-time",
    position: 1,
    requirements: ["Network Security", "SIEM", "Penetration Testing"],
    createdAt: new Date().toISOString(),
    company: { name: "SentinelGrid", logo: "" },
  },
  {
    _id: "sample-11",
    title: "Mobile App Developer (Flutter)",
    description: "Ship cross-platform mobile features for a consumer-facing app.",
    location: "Kochi",
    experienceLevel: 2,
    salary: "11",
    jobType: "Full-time",
    position: 2,
    requirements: ["Flutter", "Dart", "REST APIs"],
    createdAt: new Date().toISOString(),
    company: { name: "AppOrbit", logo: "" },
  },
  {
    _id: "sample-12",
    title: "Product Analyst Intern",
    description: "Support product decisions with usage data, funnels and experiment analysis.",
    location: "Remote",
    experienceLevel: 0,
    salary: "3.5",
    jobType: "Internship",
    position: 3,
    requirements: ["SQL", "Analytics", "Communication"],
    createdAt: new Date().toISOString(),
    company: { name: "Northbeam Labs", logo: "" },
  },
];